"""HR Documents model — labour documents generated by AI."""

import uuid
from datetime import UTC, datetime

from sqlalchemy import JSON, Column, DateTime, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

from app.db.base import Base


class HRDocument(Base):
    """Documento laboral generado por IA. Append-mostly: se crea como borrador
    y se aprueba una vez. Nunca se edita el contenido — se regenera."""

    __tablename__ = "hr_documents"
    id = Column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(PG_UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True)
    doc_type = Column(String(50), nullable=False)  # contract, nda, termination, settlement, addendum, other
    title = Column(String(255), nullable=False)
    employee_name = Column(String(200), nullable=True)
    content_html = Column(Text, nullable=False)
    status = Column(String(20), default="draft")  # draft | approved
    # Folio correlativo de gestoría, asignado al aprobar (ej. DOC-2026-0001).
    doc_number = Column(String(40), nullable=True, index=True)
    instructions = Column(Text, nullable=True)
    metadata_json = Column(JSON, nullable=True)
    # timezone=True: el modelo y el servicio insertan datetime.now(UTC) (tz-aware),
    # igual que el resto de la app. Sin esto la columna era naive (TIMESTAMP WITHOUT
    # TIME ZONE) y asyncpg rechazaba el INSERT con DataError en Postgres real (SQLite
    # no distingue naive/aware, por eso los tests no lo veían). Ver migración 0069.
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    approved_at = Column(DateTime(timezone=True), nullable=True)
