"""HR Documents model — labour documents generated by AI."""

import uuid
from datetime import datetime, timezone

from sqlalchemy import JSON, Column, DateTime, String, Text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID

from app.db.base import Base


class HRDocument(Base):
    """Documento laboral generado por IA. Append-mostly: se crea como borrador
    y se aprueba una vez. Nunca se edita el contenido — se regenera."""

    __tablename__ = "hr_documents"
    id = Column(PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    tenant_id = Column(PG_UUID(as_uuid=True), index=True, nullable=False)
    doc_type = Column(
        String(50), nullable=False
    )  # contract, nda, termination, settlement, addendum, other
    title = Column(String(255), nullable=False)
    employee_name = Column(String(200), nullable=True)
    content_html = Column(Text, nullable=False)
    status = Column(String(20), default="draft")  # draft | approved
    instructions = Column(Text, nullable=True)
    metadata_json = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
    approved_at = Column(DateTime, nullable=True)
