"""Backward-compatibility shim — implementation in queries.py / commands.py."""

from app.services.hr.commands import (
    approve_expense,
    approve_leave_request,
    # payroll writes
    approve_payroll,
    clock_in,
    clock_out_attendance,
    create_employee,
    # expense writes
    create_expense,
    # leave request writes
    create_leave_request,
    create_payroll,
    create_payroll_auto,
    delete_employee,
    # employee doc writes
    delete_employee_document,
    delete_expense,
    delete_leave_request,
    delete_payroll,
    generate_and_save_payroll_pdf,
    # special docs
    generate_finiquito_pdf,
    generate_liquidacion_pdf,
    generate_registro_jornada,
    reimburse_expense,
    reject_expense,
    reject_leave_request,
    update_employee,
    update_payroll,
    upload_employee_document,
    upload_expense_receipt,
    # schedule + attendance writes
    upsert_schedule,
)
from app.services.hr.queries import (
    UPLOAD_DIR,
    # payroll reads
    build_payroll_pdf,
    calc_payroll,
    download_payroll_pdf,
    get_currently_working,
    get_employee,
    # employee doc reads
    get_employee_document,
    get_employee_schedule,
    get_expense_receipt_path,
    list_attendance,
    list_employee_documents,
    list_employees,
    # expense reads
    list_expenses,
    # leave request reads
    list_leave_requests,
    list_payrolls,
    # schedule + attendance reads
    list_schedules,
    # special docs
    load_employee_and_tenant,
    preview_payroll,
    read_document_file,
)

__all__ = [
    "calc_payroll",
    "list_employees",
    "get_employee",
    "create_employee",
    "update_employee",
    "delete_employee",
    "list_payrolls",
    "preview_payroll",
    "build_payroll_pdf",
    "download_payroll_pdf",
    "create_payroll",
    "create_payroll_auto",
    "update_payroll",
    "delete_payroll",
    "approve_payroll",
    "generate_and_save_payroll_pdf",
    "get_employee_document",
    "list_employee_documents",
    "read_document_file",
    "upload_employee_document",
    "delete_employee_document",
    "load_employee_and_tenant",
    "generate_finiquito_pdf",
    "generate_liquidacion_pdf",
    "generate_registro_jornada",
    "UPLOAD_DIR",
    "upsert_schedule",
    "clock_in",
    "clock_out_attendance",
    "list_schedules",
    "get_employee_schedule",
    "list_attendance",
    "get_currently_working",
    "list_leave_requests",
    "create_leave_request",
    "approve_leave_request",
    "reject_leave_request",
    "delete_leave_request",
    "list_expenses",
    "get_expense_receipt_path",
    "create_expense",
    "approve_expense",
    "reject_expense",
    "reimburse_expense",
    "upload_expense_receipt",
    "delete_expense",
]
