"""Create document_embeddings table with JSONB embedding (no pgvector).

Background: 0001_initial_squash declared this table with embedding TEXT,
but installations that came from earlier dumps never executed that
specific block — the alembic_version row points at a stamp that
predates it. This migration creates the table when missing using JSONB
for the embedding (list of floats), and re-creates it if it exists with
the legacy TEXT shape so the new Python-side cosine search works
consistently across all installs.

The desktop app distributes a Postgres portable that does NOT include
the pgvector extension, so we explicitly use JSONB and compute cosine
similarity in Python (see app/agents/agent_tools/semantic_search.py).

Revision ID: 0003_doc_embeddings_jsonb
Revises: 0002_accounting_fks
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision = "0003_doc_embeddings_jsonb"
down_revision = "0002_accounting_fks"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table("document_embeddings"):
        # Legacy install: drop and recreate so the embedding column type
        # is consistent (some installs have it as TEXT, others may have
        # the pgvector type from older code, others nothing). No data
        # loss in practice — embeddings can be regenerated by re-uploading
        # documents through classify_document.
        op.drop_table("document_embeddings")

    op.create_table(
        "document_embeddings",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("tenant_id", UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_index", sa.String(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("element_type", sa.String(), nullable=True),
        sa.Column("bounding_box", JSONB(), nullable=True),
        sa.Column("jurisdiction", sa.String(20), nullable=True),
        sa.Column("embedding", JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
    )
    op.create_index(
        "ix_document_embeddings_document_id",
        "document_embeddings",
        ["document_id"],
    )
    op.create_index(
        "ix_document_embeddings_tenant_id",
        "document_embeddings",
        ["tenant_id"],
    )
    op.create_index(
        "ix_document_embeddings_jurisdiction",
        "document_embeddings",
        ["jurisdiction"],
    )


def downgrade() -> None:
    op.drop_index("ix_document_embeddings_jurisdiction", "document_embeddings")
    op.drop_index("ix_document_embeddings_tenant_id", "document_embeddings")
    op.drop_index("ix_document_embeddings_document_id", "document_embeddings")
    op.drop_table("document_embeddings")
