"""Add ui graph nodes and edges to workflows

Revision ID: 232fec5cbb97
Revises: c3fd4cbcdc0f
Create Date: 2026-03-06 08:26:19.724263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232fec5cbb97'
down_revision: Union[str, None] = 'c3fd4cbcdc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('ui_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('workflows', sa.Column('ui_edges', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'ui_edges')
    op.drop_column('workflows', 'ui_nodes')
    # ### end Alembic commands ###
