"""add_tenant_documents_table

Revision ID: 480048dde7b6
Revises: 6106ea8b058e
Create Date: 2026-02-23 19:37:46.048652

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '480048dde7b6'
down_revision: str | None = '6106ea8b058e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_documents_created_at'), 'tenant_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_tenant_documents_status'), 'tenant_documents', ['status'], unique=False)
    op.create_index(op.f('ix_tenant_documents_task_id'), 'tenant_documents', ['task_id'], unique=False)
    op.create_index(op.f('ix_tenant_documents_tenant_id'), 'tenant_documents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_documents_tenant_id'), table_name='tenant_documents')
    op.drop_index(op.f('ix_tenant_documents_task_id'), table_name='tenant_documents')
    op.drop_index(op.f('ix_tenant_documents_status'), table_name='tenant_documents')
    op.drop_index(op.f('ix_tenant_documents_created_at'), table_name='tenant_documents')
    op.drop_table('tenant_documents')
    # ### end Alembic commands ###
