"""Add_category_to_TenantDocument

Revision ID: a6bf183c8e0c
Revises: 856702bb2ab8
Create Date: 2026-02-26 07:42:47.574358

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6bf183c8e0c'
down_revision: str | None = '856702bb2ab8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_documents', sa.Column('category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tenant_documents_category'), 'tenant_documents', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_documents_category'), table_name='tenant_documents')
    op.drop_column('tenant_documents', 'category')
    # ### end Alembic commands ###
