"""add tenant_knowledge table

Revision ID: a79b087a3db7
Revises: ad8cd22d678b
Create Date: 2026-03-05 09:14:14.226171

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a79b087a3db7'
down_revision: Union[str, None] = 'ad8cd22d678b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_knowledge_key'), 'tenant_knowledge', ['key'], unique=False)
    op.create_index(op.f('ix_tenant_knowledge_tenant_id'), 'tenant_knowledge', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_knowledge_tenant_id'), table_name='tenant_knowledge')
    op.drop_index(op.f('ix_tenant_knowledge_key'), table_name='tenant_knowledge')
    op.drop_table('tenant_knowledge')
    # ### end Alembic commands ###
