"""Add domain events table

Revision ID: ad8cd22d678b
Revises: bb642129ec99
Create Date: 2026-03-05 08:37:47.397385

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ad8cd22d678b"
down_revision: Union[str, None] = "bb642129ec99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_domain_events_created_at"), "domain_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_domain_events_event_name"), "domain_events", ["event_name"], unique=False
    )
    op.create_index(
        op.f("ix_domain_events_tenant_id"), "domain_events", ["tenant_id"], unique=False
    )
    op.create_table(
        "bank_transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bank_transactions_tenant_id"), "bank_transactions", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bank_transactions_tenant_id"), table_name="bank_transactions")
    op.drop_table("bank_transactions")
    op.drop_index(op.f("ix_domain_events_tenant_id"), table_name="domain_events")
    op.drop_index(op.f("ix_domain_events_event_name"), table_name="domain_events")
    op.drop_index(op.f("ix_domain_events_created_at"), table_name="domain_events")
    op.drop_table("domain_events")
    # ### end Alembic commands ###
