"""Add start_date to Projects and ProjectTasks

Revision ID: bb642129ec99
Revises: 363b80e64875
Create Date: 2026-02-28 15:05:54.694543

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bb642129ec99'
down_revision: str | None = '363b80e64875'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_tasks', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'start_date')
    op.drop_column('project_tasks', 'start_date')
    # ### end Alembic commands ###
