"""Add locked_by and locked_at to tenant_documents

Revision ID: c3fd4cbcdc0f
Revises: 52601379920c
Create Date: 2026-03-06 08:12:15.971771

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3fd4cbcdc0f"
down_revision: Union[str, None] = "52601379920c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tenant_documents", sa.Column("locked_by", sa.UUID(), nullable=True))
    op.add_column(
        "tenant_documents", sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_documents", "locked_at")
    op.drop_column("tenant_documents", "locked_by")
    # ### end Alembic commands ###
