"""
Tablas de datos del Coordinador (clasificador de intenciones).

Contiene únicamente datos estáticos usados por ``classifier.py``: regex
compilados de normalización, mapas de keywords por dominio, tokens de
chitchat y conectores multi-step. Sin lógica — la lógica vive en
``classifier.py``, que reexporta estos nombres para compatibilidad.
"""

import re

# Patrones de normalización: tokens que NO afectan la clasificación pero rompen
# el cache hit ("crea factura 500" vs "crea factura 600" deberían ser el mismo).
_RE_EMAIL = re.compile(r"\b[\w.+-]+@[\w-]+\.[\w.-]+\b")
_RE_NIF = re.compile(r"\b[A-Z]?\d{7,8}[A-Z]?\b", re.IGNORECASE)
_RE_DATE = re.compile(r"\b(\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\d{4}[/-]\d{1,2}[/-]\d{1,2})\b")
_RE_AMOUNT = re.compile(r"\b\d[\d.,]*\s*(?:€|eur|euros?|usd|\$|%)\b", re.IGNORECASE)
_RE_NUMBER = re.compile(r"\b\d+([.,]\d+)?\b")
_RE_WHITESPACE = re.compile(r"\s+")
_RE_MONTH = re.compile(
    r"\b(enero|febrero|marzo|abril|mayo|junio|julio|" r"agosto|septiembre|octubre|noviembre|diciembre)\b",
    re.IGNORECASE,
)
_RE_QUARTER = re.compile(r"\b[qQ][1-4]\b")


# Reglas de palabras clave — usadas como fallback rápido si el LLM falla
_KEYWORD_MAP: dict[str, list[str]] = {
    "billing": [
        "factura",
        "facturar",
        "cobro",
        "pago",
        "iva",
        "presupuesto",
        "albarán",
        "emisión",
    ],
    "documents": [
        "contrato",
        "documento",
        "archivo",
        "pdf",
        "extracto",
        "subir",
        "analizar",
        "escanear",
    ],
    "compliance": [
        "modelo 303",
        "modelo 130",
        "modelo 111",
        "modelo 200",
        "modelo 390",
        "hacienda",
        "aeat",
        "impuesto",
        "declaración trimestral",
        "declaración del iva",
    ],
    "hr": [
        "nómina",
        "nóminas",
        "empleado",
        "laboral",
        "vacaciones",
        "baja médica",
        "trabajador",
        "salario",
        "sueldo",
        "contrato laboral",
    ],
    "crm": [
        "venta",
        "oportunidad",
        "lead",
        "cliente potencial",
        "nuevo cliente",
        "alta de cliente",
        "alta del cliente",
        "añade un cliente",
        "añadir cliente",
        "registra un cliente",
        "registrar cliente",
        "crea un cliente",
        "crear cliente",
        "crea cliente",
        "agrega un cliente",
        "agregar cliente",
        "da de alta un cliente",
        "presupuestar",
        "reunión comercial",
        "embudo",
        "trato",
        "ganada",
    ],
    "banking": [
        "saldo",
        "balance",
        "cuenta",
        "cuentas",
        "banco",
        "transacción",
        "movimiento",
        "transferencia",
        "informe bancario",
        "iban",
        "psd2",
        "extracto bancario",
    ],
    "rag": [
        "qué dice",
        "qué dicen",
        "qué hay sobre",
        "qué tenemos sobre",
        "qué información",
        "qué dice nuestra",
        "según el contrato",
        "según el documento",
        "según los documentos",
        "según la política",
        "política interna",
        "consultar documento",
        "consultar la documentación",
        "preguntar a la documentación",
        "pregúntale a la documentación",
        "busca en los documentos",
        "resume el documento",
        "qué significa",
    ],
    "excel": ["excel", "csv", "cruzar", "tabla", "hoja de cálculo", "datos", "columnas"],
    "email": [
        "correo electrónico",
        "bandeja de entrada",
        "buzón",
        "inbox",
        "enviar mensaje",
        "responder correo",
    ],
    "coordinator": [
        "coordinar",
        "complejo",
        "varios agentes",
        "múltiple",
        "todos los agentes",
        "combina",
        "cruza",
    ],
    "workflow": [
        "automatiza",  # stem: cubre automatiza/automatizar/automatización/automatizaciones
        "regla",
        "cada vez que",
        "programar",
        "automático",
        "workflow",
        "repetir",
        "cada fin de mes",
    ],
    "recruitment": [
        "reclutamiento",
        "candidato",
        "cv",
        "currículum",
        "curriculum",
        "puesto abierto",
        "selección de personal",
        "contratar",
        "vacante",
        "entrevista",
        "recruiting",
        "shortlist",
    ],
    "marketing": [
        "marketing",
        "contenido",
        "redes sociales",
        "instagram",
        "facebook",
        "linkedin",
        "publicación",
        "post",
        "hashtag",
        "plan de contenidos",
        "campaña",
        "social media",
        "community manager",
    ],
    "accounting": [
        "asiento",
        "asiento contable",
        "libro diario",
        "contabilidad",
        "cuenta contable",
        "pgc",
        "amortización",
        "balance de situación",
        "pérdidas y ganancias",
        "inmovilizado",
        "activo fijo",
        "debe",
        "haber",
        "conciliación contable",
    ],
    "inventory": [
        "stock",
        "inventario",
        "almacén",
        "almacen",
        "existencias",
        "producto",
        "productos",
        "sku",
        "código de barras",
        "codigo de barras",
        "recuento",
        "reposición",
        "reposicion",
        "punto de pedido",
        "stock mínimo",
        "stock minimo",
        "merma",
        "mermas",
        "valoración de stock",
        "entrada de mercancía",
        "salida de mercancía",
        "ajuste de stock",
        "actualizar precios",
        "subir precios",
        "lote de productos",
    ],
    "report": [
        "informe mensual",
        "snapshot",
        "resumen del mes",
        "resumen mensual",
        "resumen contable",
        "resumen del trimestre",
        "resumen trimestral",
        "resumen anual",
        "resumen del año",
        "estado de la empresa",
        "informe completo",
        "informe empresarial",
        "análisis mensual",
        "cierre mensual",
        "genera el informe",
        "informe de gestión",
        "dame el resumen",
        "dame un resumen",
    ],
    "chat": [
        "qué es",
        "cómo funciona",
        "explica",
        "diferencia entre",
        "qué significa",
        "ayuda",
        "terminó",
        "ha terminado",
        "estado de la tarea",
        "cómo va",
        "qué tal va",
        "puedes",
        "sabes",
        "entiendes",
        "gracias",
        "hola",
        "buenas",
    ],
}


_CHITCHAT_TOKENS = {
    "hola",
    "buenas",
    "buenos días",
    "buenas tardes",
    "buenas noches",
    "gracias",
    "ok",
    "vale",
    "qué tal",
    "cómo estás",
}

# Strong keywords: si alguno matchea → dominio devuelto directamente sin scoring.
# Solo poner aquí términos altamente predictivos del dominio (alta precisión, baja
# ambigüedad). Si dudas si añadir uno, NO lo añadas — déjalo en _KEYWORD_MAP.
# Desambiguación: cuando hay strong en varios dominios gana el keyword MÁS LARGO
# (maximal-munch, proxy de especificidad — ver _strong_keyword_match); el orden de
# este dict solo desempata longitudes iguales. Por eso un término específico
# ('modelo 303') vence a uno genérico ('qué dice') aunque rag aparezca antes.
_STRONG_KEYWORDS: dict[str, list[str]] = {
    # Acciones específicas primero
    "rag": [
        "qué dice",
        "qué dicen",
        "qué hay sobre",
        "qué tenemos sobre",
        "qué información tenemos",
        "según el contrato",
        "según el documento",
        "según los documentos",
        "según la política",
        "política interna",
        "consultar la documentación",
        "preguntar a la documentación",
        "pregúntale a la documentación",
        "busca en los documentos",
        "resume el documento",
    ],
    "compliance": ["modelo 303", "modelo 130", "modelo 111", "modelo 200", "modelo 390", "aeat", "hacienda"],
    "banking": [
        "iban",
        "concilia",
        "concilia movimiento",
        "extracto bancario",
        "resumen financiero",
        "estado financiero",
        "saldo de la cuenta",
        "transferencia",
    ],
    "email": [
        "envía un email",
        "envía email",
        "envía un correo",
        "envía correo",
        "manda un email",
        "manda email",
        "manda un correo",
        "responde el correo",
        "responde el email",
        "bandeja de entrada",
        "revisa el inbox",
    ],
    "workflow": [
        "crea un workflow",
        "automatiza",
        "workflow",
        "cada lunes",
        "cada martes",
        "cada miércoles",
        "cada jueves",
        "cada viernes",
        "cada día",
        "cada semana",
        "cada fin de mes",
    ],
    "documents": [
        "escanea",
        "escanear este",
        "sube este pdf",
        "sube este documento",
        "clasifica los documentos",
        "clasifica el documento",
    ],
    "recruitment": [
        "candidato",
        "currículum",
        "shortlist",
        "selección de personal",
        "vacante",
        "oferta de trabajo",
        "publica una oferta",
        "publicar una oferta",
        "puesto vacante",
    ],
    "marketing": ["campaña de marketing", "redes sociales", "instagram", "linkedin"],
    "excel": ["excel", "csv", "hoja de cálculo"],
    "accounting": [
        "asiento contable",
        "libro diario",
        "crea un asiento",
        "asiento de",
        "balance de situación",
        "pérdidas y ganancias",
        "cuenta contable",
        "inmovilizado",
        "activo fijo",
        "amortización del inmovilizado",
    ],
    "inventory": [
        "ajuste de stock",
        "ajusta el stock",
        "recuento de inventario",
        "valoración del inventario",
        "productos bajo mínimo",
        "stock mínimo",
        "actualizar precios",
        "sube los precios",
        "entrada de mercancía",
        "salida de mercancía",
        "stock del producto",
        "cuánto stock",
    ],
    "report": [
        "informe mensual",
        "snapshot",
        "estado de la empresa",
        "cierre mensual",
        "resumen contable",
        "resumen del mes",
        "resumen mensual",
        "resumen del trimestre",
        "resumen trimestral",
        "resumen anual",
    ],
    # CRM-create antes de billing — "factura" es strong de billing y dispararía
    # en prompts como "crea cliente y emítele factura"; pero el conector multi-step
    # ya delega ese caso al LLM (path coordinator). Aquí cubrimos los CRM-create
    # puros que sin esto caían al LLM y este los clasificaba mal como billing.
    "crm": [
        "crea un cliente",
        "crear cliente",
        "crea cliente",
        "registra un cliente",
        "registrar cliente",
        "añade un cliente",
        "añadir cliente",
        "da de alta un cliente",
        "alta del cliente",
        "alta de cliente",
        "agrega un cliente",
        "agregar cliente",
    ],
    # Dominios "objeto/recurso" al final (pueden aparecer como complemento de acción)
    "hr": [
        "nómina",
        "nóminas",
        "da de alta empleado",
        "alta del empleado",
        "alta de empleado",
        "contrato indefinido",
        "contrato temporal",
        "contrato fijo discontinuo",
    ],
    "billing": ["factura", "facturas", "cobro de", "presupuesto"],
}


_MULTI_STEP_CONNECTORS = (
    " y luego ",
    " y después ",
    " y envía",
    " y manda",
    " y prepara",
    " y genera",
    " y crea",
    " y notifica",
    " también ",
    ", luego ",
    ", después ",
    " después de ",
)
